#!/bin/sh

## Super Minimal fetch program (sfetch)

deref() {
    eval echo "\$$1"
}
elem() {
    # shellcheck disable=SC2059 # the only way
    printf "$2" | sed "$1!d"
}

# all colors
blue="\033[34m"
brightblue="\033[94m"
cyan="\033[36m"
brightcyan="\033[96m"
brightblack="\033[90m"
red="\033[31m"
brightred="\033[91m"
yellow="\033[33m"
brightyellow="\033[93m"
magenta="\033[35m"
brightmagenta="\033[95m"
green="\033[32m"
brightgreen="\033[92m"
white="\033[37m"
brightwhite="\033[97m"
xx="\033[0m" # reset
zz="\033[1m" # bold

## Getting OS name
OS="$(. /etc/os-release && echo "$PRETTY_NAME")"
OS_LOWER="$(echo $OS | tr '[:upper:]' '[:lower:]')"

## Getting Kernel version + arch
Kernel="$(uname -rm)"

## Uptime
Uptime="$(uptime -p | sed 's/up //; s/,//g')"

## Shell
Shell="$(basename "$SHELL")"

## Hostname
HOSTNAME=$(uname -n)

## DE or WM
Desktop="$(
         de=$(echo "${XDG_CURRENT_Desktop:-$DESKTOP_SESSION}" | awk -F/ '{ print tolower($NF) }')
        if [ "$de" ] && echo "$de" | grep -Fq "none" || [ -z "$de" ]; then
            if [ "$WAYLAND_DISPLAY" ]; then
                wm="$(pgrep -lox "cage.*|cardboard|dwl|enlightenment|grefsen|
                        |hikari|kwin|mutter|river|sway|velox|wayfire|waymonad|
                        |weston|wio" | cut -d' ' -f2)"
            else
                # firstly getting root window id (WM) and then getting WM name, ignoring unimportant stuff
                # some WM do not have proper set atoms like _NET_SUPPORTING_WM_CHECK and _NET_WM_NAME
                # this workaround allows to detect such WM
                wm_id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>/dev/null) &&
                wm="$(xprop -id "${wm_id##* }" _NET_WM_NAME 2>/dev/null |
                            awk '{ print tolower($NF) }' | xargs)"
                [ "$wm" ] ||
                    wm=$(ps -eo comm= | grep -m 1 -o -e "2bwm"      \
                                                     -e "catwm"     \
                                                     -e "dwm"       \
                                                     -e "fvwm"      \
                                                     -e "monsterwm" \
                                                     -e "sowm"      \
                                                     -e "tinywm"    \
                                                     -e "wmaker"    \
                                                     -e "xmonad")
            fi
            echo "$wm"
        else
            echo "$de"
        fi
)"

# Packages
packages_apk() { apk info 2>/dev/null | wc -l; }
packages_dpkg() { dpkg -l 2>/dev/null | grep -c "^ii"; }
packages_pacman() { pacman -Qq 2>/dev/null | wc -l; }
packages_rpm() { rpm -qa 2>/dev/null | wc -l; }
packages_zypper() { zypper se --installed-only 2>/dev/null | wc -l; }
packages_xbps() { xbps-query -l 2>/dev/null | wc -l; }
packages_emerge() { find /var/db/pkg -mindepth 2 -maxdepth 2 2>/dev/null | wc -l; }
Packages="$(
    case $OS_LOWER in
        alpine*|postm*) packages_apk;;
        android*|astra*|*bian*|elementary*|*mint*|mx*|*buntu*|zorin*|kali*|devuan*)
            packages_dpkg;;
        arc*|artix*|endeavour*|manjaro*|garuda*|parabola*)
            packages_pacman;;
        fedora*|qubes*|cent*|redhat*) packages_rpm;;
        *ntoo*) packages_emerge;;
        Void*) packages_xbps;;
	*suse*) packages_opensuse;;
    esac)"


## ASCII arts, im not cool in them

IFS=
case "${LOGO:-$OS}" in
	*)
	motif="$brightyellow"
	a="$brightblack"
	b="$yellow"
	read -r LOGO <<EOF
        ${a}XXXX$xx      \n\
       ${a}X$xx${zz}0$xx${a}XX$xx${zz}0$xx${a}X$xx     \n\
       ${a}X$xx${b}<XX>$xx${a}X$xx     \n\
     ${a}XX${xx}X${a}XXXX${xx}X${a}XX$xx   \n\
    ${a}XX${xx}XXXXXXXX${a}XX$xx  \n\
   ${a}XX${xx}XXXXXXXXXX${a}XX$xx \n\
  ${b}I$xx${a}XXX${xx}XXXXXXXX${a}XXX$xx${b}I$xx\n\
  ${b}IL>$xx${a}XX${xx}XXXXXX$xx${a}XX$xx${b}<JI$xx\n
EOF
  ;;
esac
unset IFS
motif=$motif$zz

INFO="$motif${USERNAME:-${USER:-${LOGNAME:-$(whoami)}}}$xx @ $motif$HOSTNAME$xx"
valign() {
    awk "BEGIN { while (i++ < 10 - length(\"$1\")) printf \" \" }"
}
for i in OS Kernel Uptime Packages Shell Desktop; do
    v="$(deref "$i")"
    [ "$v" ] &&
        INFO="$INFO
${motif}$i:$xx$(valign "$i")$v"
done

for i in $(seq 8); do
    echo "${INFO_ONLY-"$(elem "$i" "$LOGO")  | "}$(elem "$i" "$INFO")"
done
